FitnessCommunity/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FitnessCommunity.Data;
using FitnessCommunity.Models;
using FitnessCommunity.Models.ViewModels;
using FitnessCommunity.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FitnessCommunity.Controllers
{
    [Authorize]
    public class TableController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IWeigtLogManageService _weigtLogManageService;
        private readonly IApplicationUserService _applicationUserService;

        public TableController(IMapper mapper, IWeigtLogManageService weigtLogManageService,
                                    IApplicationUserService applicationUserService)
        {
            _mapper = mapper;
            _weigtLogManageService = weigtLogManageService;
            _applicationUserService = applicationUserService;
        }
        public async Task<IActionResult> Index()
        {
            ApplicationUser user = await _applicationUserService.GetUserByName(this.User.Identity.Name);
            IEnumerable<TableWeightLogViewModel> tableWeightLogsViewModel =
                _mapper.Map<IEnumerable<TableWeightLogViewModel>>(await _weigtLogManageService.GetAllWeightLogs(user));

            if (user.MeasureType == Enums.MeasureType.lbs)
                tableWeightLogsViewModel = tableWeightLogsViewModel.Select(log => 
                                {
                                    var logForConvert = _mapper.Map<WeightLog>(log);
                                    log.WeightValue = WeightConverter.ConvertToLbs(logForConvert).WeightValue;
                                    return log;
                                });

            return View(tableWeightLogsViewModel);
        }
    }
}

FitnessCommunity/Controllers/WeightLogController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FitnessCommunity.Models;
using FitnessCommunity.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;
using FitnessCommunity.Services;

namespace FitnessCommunity.Controllers
{
    [Authorize]
    public class WeightLogController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IWeigtLogManageService _weigtLogManageService;
        private readonly IApplicationUserService _applicationUserService;

        public WeightLogController(IMapper mapper, IWeigtLogManageService weigtLogManageService,
                                    IApplicationUserService applicationUserService)
        {
            _mapper = mapper;
            _weigtLogManageService = weigtLogManageService;
            _applicationUserService = applicationUserService;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ApplicationUser user = await _applicationUserService.GetUserByName(this.User.Identity.Name);
            ViewBag.MeasureType = user.MeasureType;
            return View(new WeightLogViewModel {
                LogDate = DateTime.Now
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WeightLogViewModel weightLogViewModel )
        {
            if (ModelState.IsValid)
            {
                WeightLog newWeightLog = _mapper.Map<WeightLog>(weightLogViewModel);

                var user = await _applicationUserService.GetUserByName(this.User.Identity.Name);

                newWeightLog.User = user;
                newWeightLog = user.MeasureType == Enums.MeasureType.lbs ? WeightConverter.ConvertToKg(newWeightLog) : newWeightLog;

                await _weigtLogManageService.Add(newWeightLog);

                return RedirectToAction(nameof(TableController.Index), "Table"); ;
            }

            return View(weightLogViewModel);
        }

        
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            WeightLog weightLog = await _weigtLogManageService.FindWeightLogById(id);

            var user = await _applicationUserService.GetUserByName(this.User.Identity.Name);
            ViewBag.MeasureType = user.MeasureType;
            if (user.MeasureType == Enums.MeasureType.lbs)
                weightLog = WeightConverter.ConvertToLbs(weightLog);

            WeightLogViewModel weightLogViewModel = _mapper.Map<WeightLogViewModel>(weightLog);
            return View(weightLogViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
       public async Task<IActionResult> Edit(TableWeightLogViewModel weightLogViewModel)
        {
            var user = await _applicationUserService.GetUserByName(this.User.Identity.Name);

            if (user.MeasureType == Enums.MeasureType.lbs)
                weightLogViewModel.WeightValue = WeightConverter.ConvertToKg(_mapper.Map<WeightLog>(weightLogViewModel)).WeightValue;

            await _weigtLogManageService.UpdateWeightLog(weightLogViewModel);

            return RedirectToAction(nameof(TableController.Index),"Table");
        }
        
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            WeightLog weightLog = await _weigtLogManageService.FindWeightLogById(id);

            await _weigtLogManageService.Remove(weightLog);

            return RedirectToAction(nameof(TableController.Index), "Table");
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FitnessCommunity/Views/Table/Index.cshtml
@model IEnumerable<TableWeightLogViewModel>
@inject UserManager<ApplicationUser> userManager;
@{
    var user = (await userManager.FindByNameAsync(User.Identity.Name)) as ApplicationUser;
    ViewBag.MeasureType = user.MeasureType;
}
<link type="text/css" rel="stylesheet" href="~/css/table/style.css" />

<div style="width:60%">

    <table class="table table-striped table-hover table-responsive" id="weightLogsTable">
        <thead>
            <tr class="text-uppercase" id="tableHeader">
                <th>
                    Date
                    <span class="glyphicon glyphicon-sort-by-attributes"></span>
                </th>
                <th>
                    Weight in @ViewBag.MeasureType <span class="glyphicon glyphicon-sort-by-order"></span>
                </th>
            </tr>
        </thead>

        <tbody>
            @{
                foreach (var log in Model)
                {
                    <tr>
                        <td>
                            @log.LogDate.ToShortDateString()
                        </td>
                        <td class="right-row">
                            <label> @Decimal.Round((Decimal)log.WeightValue,2)</label>
                            <a asp-area="" asp-controller="WeightLog" asp-action="Delete" asp-route-id="@log.Id" class="btn btn-info btn-xs">Delete</a>
                            <a asp-area="" asp-controller="WeightLog" asp-action="Edit" asp-route-id="@log.Id" class="btn btn-primary btn-xs">Edit</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

@section Scripts
    {
    <script>
        $.fn.dataTableExt.oSort["date-format-desc"] = function (x, y) {
            x = new Date(x);
            y = new Date(y);

            return x > y ? -1 : 1;
        };

        $.fn.dataTableExt.oSort["date-format-asc"] = function (x, y) {
            x = new Date(x);
            y = new Date(y);

            return x > y ? 1 : -1;
        }
        $.fn.dataTableExt.oSort["weight-desc"] = function (x, y) {
            x = parseFloat($($($(x)).filter('label')).text());
            y = parseFloat($($($(y)).filter('label')).text());

            return x > y ? -1 : 1;
        };

        $.fn.dataTableExt.oSort["weight-asc"] = function (x, y) {
            x = parseFloat($($($(x)).filter('label')).text());
            y = parseFloat($($($(y)).filter('label')).text());

            return x > y ? 1 : -1;
        }

        
        $(document).ready(function () {
            $('#weightLogsTable').DataTable({
                columnDefs: [
                    { type: 'date-format', targets: 0 },
                    { type: 'weight', targets: 1 }
                ]
            } );
        });
    </script>
}